# Generated by Django 4.2.4 on 2023-08-30 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(choices=[(1, 'Late'), (2, 'Somewhat Late'), (3, 'On Time'), (4, 'Somewhat Early'), (5, 'Very Early')])),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bus.bus')),
                ('stop_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bus.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
