# Generated by Django 4.2.4 on 2023-08-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
        ('reviews', '0003_rename_comments_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stop_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bus.busstop'),
        ),
    ]
