# Generated by Django 4.2.4 on 2023-08-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_stop_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='full_name',
            field=models.CharField(default='olaide', max_length=255),
            preserve_default=False,
        ),
    ]
