# Generated by Django 4.2.4 on 2023-11-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_alter_busroute_id'),
        ('reviews', '0005_remove_review_user_review_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='arrival_time',
            field=models.TimeField(blank=True, default='17:00', verbose_name='Arrival Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='bus_id',
            field=models.CharField(max_length=10),
        ),
        migrations.RemoveField(
            model_name='review',
            name='stop_point',
        ),
        migrations.AddField(
            model_name='review',
            name='stop_point',
            field=models.ManyToManyField(to='bus.busroute'),
        ),
    ]
