# Generated by Django 4.2.4 on 2023-11-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_alter_busroute_id'),
        ('reviews', '0006_review_arrival_time_alter_review_bus_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stop_point',
        ),
        migrations.AddField(
            model_name='review',
            name='stop_point',
            field=models.ForeignKey(default='37027392', on_delete=django.db.models.deletion.PROTECT, to='bus.busroute'),
            preserve_default=False,
        ),
    ]
