# Generated by Django 4.2.4 on 2023-11-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_remove_review_stop_point_review_stop_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stop_point',
            field=models.CharField(max_length=255),
        ),
    ]
