# Generated by Django 4.2.4 on 2024-01-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_review_stop_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='common_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
