# Generated by Django 4.2.4 on 2024-01-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_review_common_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='arrival_time',
            field=models.TimeField(verbose_name='Arrival Time'),
        ),
    ]
