# Generated by Django 4.2.4 on 2024-01-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_review_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='arrival_time',
            field=models.TimeField(blank=True, verbose_name='Arrival Time'),
        ),
    ]
