# Generated by Django 4.2.4 on 2023-10-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcode',
            name='stop_point',
        ),
    ]
