# Generated by Django 4.2.4 on 2023-11-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_remove_postcode_stop_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCode',
        ),
    ]
