# Generated by Django 4.2.4 on 2023-11-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_delete_postcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_point', models.BigIntegerField(unique=True)),
                ('common_name', models.CharField(max_length=255)),
                ('bus_id', models.CharField(max_length=20)),
                ('arrival_time', models.TimeField(verbose_name='Arrival Time')),
            ],
        ),
    ]
