# Generated by Django 4.2.4 on 2023-11-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_busroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='stop_point',
            field=models.BigIntegerField(max_length=20),
        ),
        
        
    ]
