# Generated by Django 4.2.4 on 2023-11-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_alter_busroute_stop_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusRoute',
        ),
    ]
