# Generated by Django 4.2.4 on 2023-11-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_busroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
