# Generated by Django 4.2.4 on 2023-12-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_alter_busroute_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
