# Generated by Django 4.2.4 on 2023-12-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 12:00:00'),
            preserve_default=False,
        ),
    ]
